/*
TOTVS NORDESTE
Consultor Especialista: Italo Ribeiro
Processo de Controle de EPI no Fluig
*/

SELECT B.CODTIPO,
       B.CODCOLIGADA,
       B.CODFILIAL,
       G.NOMEFANTASIA                     AS FILIAL,
       B.CODPESSOA,
       B.CHAPA,
       B.NOME,
       B.DATAADMISSAO,
       CONCAT(F.CODCCUSTO, '|', F.NOME)   AS CENTRODECUSTO,
       CONCAT(D.CODIGO, '|', D.NOME)      AS FUNCAO,
       CONCAT(E.CODIGO, '|', E.DESCRICAO) AS SECAO,
       E.NROCENCUSTOCONT,
       ISNULL(X.QTDEPI,0) AS QTD
FROM   PPESSOA A WITH (NOLOCK)
       JOIN PFUNC B WITH (NOLOCK)
         ON A.CODIGO = B.CODPESSOA
       JOIN GUSUARIO C WITH (NOLOCK)
         ON C.CODUSUARIO = A.CODUSUARIO
       JOIN PFUNCAO D WITH (NOLOCK)
         ON D.CODCOLIGADA = B.CODCOLIGADA
            AND D.CODIGO = B.CODFUNCAO
       JOIN PSECAO E WITH (NOLOCK)
         ON E.CODCOLIGADA = B.CODCOLIGADA
            AND E.CODIGO = B.CODSECAO
       JOIN GCCUSTO F WITH (NOLOCK)
         ON F.CODCOLIGADA = D.CODCOLIGADA
            AND F.CODCCUSTO = E.NROCENCUSTOCONT
       JOIN GFILIAL G WITH (NOLOCK)
         ON G.CODCOLIGADA = B.CODCOLIGADA
            AND G.CODFILIAL = B.CODFILIAL
       LEFT JOIN (SELECT CODPESSOA,
                         COUNT(*) AS QTDEPI
                  FROM   VEMPRESTIMOEPI
                  WHERE  
                  DATADEVOLUCAO IS NULL
                  AND IDDESCARTE IS NULL
                  GROUP  BY CODPESSOA) X
              ON X.CODPESSOA = B.CODPESSOA
WHERE  B.CODCOLIGADA = 1
       AND B.CODSITUACAO <> 'D'
       AND B.CODTIPO = 'N'
       AND B.NOME LIKE '%' +:NOME +'%'
