
SELECT 
A.CODCOLIGADA,
A.CODFILIAL,
E.NOMEFANTASIA COLIGADA,
D.NOMEFANTASIA AS FILIAL,
A.CODSECAO,
B.DESCRICAO AS SECAO,
B.ESTADO,
A.CODFUNCAO,
C.NOME AS FUNCAO,
A.CODSINDICATO,
F.NOME SINDICATO
FROM PFUNC A
JOIN PSECAO B ON A.CODCOLIGADA=B.CODCOLIGADA  AND A.CODSECAO=B.CODIGO 
JOIN PFUNCAO C ON C.CODCOLIGADA=A.CODCOLIGADA AND C.CODIGO=A.CODFUNCAO
JOIN GFILIAL D ON D.CODCOLIGADA=A.CODCOLIGADA AND D.CODFILIAL=A.CODFILIAL
JOIN GCOLIGADA E ON E.CODCOLIGADA=A.CODCOLIGADA 
JOIN PSINDIC F ON F.CODCOLIGADA=A.CODCOLIGADA AND F.CODIGO=A.CODSINDICATO


WHERE 
A.CODSITUACAO<>'D'
AND A.CODCOLIGADA IN (1,4,7)
GROUP BY 
A.CODCOLIGADA,
A.CODFILIAL,
E.NOMEFANTASIA,
D.NOMEFANTASIA ,
A.CODSECAO,
B.DESCRICAO,
B.ESTADO,
A.CODFUNCAO,
C.NOME,
A.CODSINDICATO,
F.NOME 



/*
SELECT 
A.CODCOLIGADA,
A.CODFILIAL,
E.NOMEFANTASIA COLIGADA,
D.NOMEFANTASIA AS FILIAL,
A.CHAPA,
A.NOME AS COLABORADOR,
A.CODSECAO,
B.DESCRICAO AS SECAO,
B.ESTADO,
A.CODFUNCAO,
C.NOME AS FUNCAO,
A.CODSINDICATO,
F.NOME SINDICATO
FROM PFUNC A
JOIN PSECAO B ON A.CODCOLIGADA=B.CODCOLIGADA  AND A.CODSECAO=B.CODIGO 
JOIN PFUNCAO C ON C.CODCOLIGADA=A.CODCOLIGADA AND C.CODIGO=A.CODFUNCAO
JOIN GFILIAL D ON D.CODCOLIGADA=A.CODCOLIGADA AND D.CODFILIAL=A.CODFILIAL
JOIN GCOLIGADA E ON E.CODCOLIGADA=A.CODCOLIGADA 
JOIN PSINDIC F ON F.CODCOLIGADA=A.CODCOLIGADA AND F.CODIGO=A.CODSINDICATO


WHERE 
A.CODSITUACAO<>'D'
AND A.CODCOLIGADA IN (1,4,7)
*/
