
SELECT 
B.CODCOLIGADA,
A.CODIGO CODPESSOA,
Z.USER_CODE,
B.CHAPA,
A.CODUSUARIO,
C.USERID,
A.NOME,
B.CODSITUACAO,
B.CODTIPO,
(
        SELECT MAX(F.DATAFIM) 
        FROM PFUFERIASPER F 
        WHERE F.CODCOLIGADA = B.CODCOLIGADA 
          AND F.CHAPA = B.CHAPA
    ) AS DATAFIMFERIAS
FROM PPESSOA A (NOLOCK) 
LEFT JOIN PFUNC B (NOLOCK) ON A.CODIGO=B.CODPESSOA
LEFT JOIN GUSUARIO C (NOLOCK) ON C.CODUSUARIO=A.CODUSUARIO
LEFT JOIN [LKD_FLUIG].[CXRCQ9_147629_FL_PD].[dbo].FDN_USERTENANT Z 
    ON Z.USER_CODE COLLATE SQL_Latin1_General_CP1_CI_AI = C.USERID COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE
B.CODSITUACAO IN('A','F')
AND B.CODTIPO NOT IN ('T','Z')
AND C.STATUS=1

